name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      # https://github.com/marketplace/actions/alibaba-cloud-container-registry-acr-login
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build draw image
        run: docker build . --build-arg NPM_TOKEN=${{secrets.NPM_TOKEN}} --build-arg BRANCH=${{steps.vars.outputs.tag}} --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/datalet/simpledraw-draw:${{steps.vars.outputs.tag}}

      - name: Push drawimage
        run: |-
          docker push registry.cn-hangzhou.aliyuncs.com/datalet/simpledraw-draw:${{steps.vars.outputs.tag}}
